console.log("Hello World");
console.log(typeof("Anjana"));
console.log(typeof(30));
console.log(typeof(33.33));
console.log('---------------------');
console.log('Hai'+ ' Anjana');
console.log('hi'+100);
console.log(6+44);
console.log('4'+'100');
console.log('---------------------');
console.log("Variables");
x = 'Anjans';
console.log(x);